local uri = require("neodap.sdk.uri")

describe("URI Module", function()
    describe("parse()", function()
        describe("type:id syntax", function()
            it("should parse file:// URIs", function()
                local parsed = uri.parse("file:///home/user/app.py")
                assert.is_not_nil(parsed)
                assert.are.equal("file", parsed.scheme)
                assert.are.equal(1, #parsed.segments)
                assert.are.equal("source", parsed.segments[1].type)
                assert.are.equal("id", parsed.segments[1].accessor)
                assert.are.equal("/home/user/app.py", parsed.segments[1].value)
            end)

            it("should parse dap:source URIs", function()
                local parsed = uri.parse("dap:source:stdlib.py:fuzzy-tiger")
                assert.is_not_nil(parsed)
                assert.are.equal("dap", parsed.scheme)
                assert.are.equal(1, #parsed.segments)
                assert.are.equal("source", parsed.segments[1].type)
                assert.are.equal("id", parsed.segments[1].accessor)
                assert.are.equal("stdlib.py:fuzzy-tiger", parsed.segments[1].value)
            end)

            it("should parse dap:session URIs", function()
                local parsed = uri.parse("dap:session:fluffy-kitten")
                assert.is_not_nil(parsed)
                assert.are.equal("dap", parsed.scheme)
                assert.are.equal(1, #parsed.segments)
                assert.are.equal("session", parsed.segments[1].type)
                assert.are.equal("fluffy-kitten", parsed.segments[1].value)
            end)

            it("should parse dap:breakpoint URIs", function()
                local parsed = uri.parse("dap:breakpoint:amber-sunset")
                assert.is_not_nil(parsed)
                assert.are.equal("breakpoint", parsed.segments[1].type)
                assert.are.equal("amber-sunset", parsed.segments[1].value)
            end)

            it("should parse dap:filter URIs", function()
                local parsed = uri.parse("dap:filter:python:raised")
                assert.is_not_nil(parsed)
                assert.are.equal("filter", parsed.segments[1].type)
                assert.are.equal("python:raised", parsed.segments[1].value)
            end)

            it("should parse session/thread URIs", function()
                local parsed = uri.parse("dap:session:fluffy-kitten/thread:1")
                assert.is_not_nil(parsed)
                assert.are.equal(2, #parsed.segments)
                assert.are.equal("session", parsed.segments[1].type)
                assert.are.equal("fluffy-kitten", parsed.segments[1].value)
                assert.are.equal("thread", parsed.segments[2].type)
                assert.are.equal("id", parsed.segments[2].accessor)
                assert.are.equal("1", parsed.segments[2].value)
            end)

            it("should parse session/thread/stack URIs", function()
                local parsed = uri.parse("dap:session:fluffy-kitten/thread:1/stack:3")
                assert.is_not_nil(parsed)
                assert.are.equal(3, #parsed.segments)
                assert.are.equal("session", parsed.segments[1].type)
                assert.are.equal("thread", parsed.segments[2].type)
                assert.are.equal("stack", parsed.segments[3].type)
                assert.are.equal("3", parsed.segments[3].value)
            end)

            it("should parse session/frame URIs (minimal path)", function()
                local parsed = uri.parse("dap:session:fluffy-kitten/frame:42")
                assert.is_not_nil(parsed)
                assert.are.equal(2, #parsed.segments)
                assert.are.equal("session", parsed.segments[1].type)
                assert.are.equal("frame", parsed.segments[2].type)
                assert.are.equal("42", parsed.segments[2].value)
            end)

            it("should parse session/frame/scope URIs", function()
                local parsed = uri.parse("dap:session:fluffy-kitten/frame:42/scope:Locals")
                assert.is_not_nil(parsed)
                assert.are.equal(3, #parsed.segments)
                assert.are.equal("frame", parsed.segments[2].type)
                assert.are.equal("scope", parsed.segments[3].type)
                assert.are.equal("Locals", parsed.segments[3].value)
            end)

            it("should parse session/binding URIs", function()
                local parsed = uri.parse("dap:session:fluffy-kitten/binding:amber-sunset")
                assert.is_not_nil(parsed)
                assert.are.equal(2, #parsed.segments)
                assert.are.equal("binding", parsed.segments[2].type)
                assert.are.equal("amber-sunset", parsed.segments[2].value)
            end)

            it("should parse session/source-binding URIs (encoded path)", function()
                -- Path is percent-encoded (slashes become %2F)
                local parsed = uri.parse("dap:session:fluffy-kitten/source-binding:%2Fhome%2Fuser%2Fapp.py")
                assert.is_not_nil(parsed)
                assert.are.equal(2, #parsed.segments)
                assert.are.equal("source-binding", parsed.segments[2].type)
                -- Parser decodes the segments
                assert.are.equal("/home/user/app.py", parsed.segments[2].value)
            end)

            it("should parse session/filter-binding URIs", function()
                local parsed = uri.parse("dap:session:fluffy-kitten/filter-binding:uncaught")
                assert.is_not_nil(parsed)
                assert.are.equal(2, #parsed.segments)
                assert.are.equal("filter-binding", parsed.segments[2].type)
                assert.are.equal("uncaught", parsed.segments[2].value)
            end)

            it("should parse session/output URIs", function()
                local parsed = uri.parse("dap:session:fluffy-kitten/output:15")
                assert.is_not_nil(parsed)
                assert.are.equal(2, #parsed.segments)
                assert.are.equal("output", parsed.segments[2].type)
                assert.are.equal("15", parsed.segments[2].value)
            end)
        end)

        describe("type[n] syntax", function()
            it("should parse session[0] URIs", function()
                local parsed = uri.parse("dap:session[0]")
                assert.is_not_nil(parsed)
                assert.are.equal(1, #parsed.segments)
                assert.are.equal("session", parsed.segments[1].type)
                assert.are.equal("index", parsed.segments[1].accessor)
                assert.are.equal(0, parsed.segments[1].value)
            end)

            it("should parse frame[0] (all top frames)", function()
                local parsed = uri.parse("dap:frame[0]")
                assert.is_not_nil(parsed)
                assert.are.equal(1, #parsed.segments)
                assert.are.equal("frame", parsed.segments[1].type)
                assert.are.equal("index", parsed.segments[1].accessor)
                assert.are.equal(0, parsed.segments[1].value)
            end)

            it("should parse session:xxx/frame[0] (top frames in session)", function()
                local parsed = uri.parse("dap:session:fluffy-kitten/frame[0]")
                assert.is_not_nil(parsed)
                assert.are.equal(2, #parsed.segments)
                assert.are.equal("session", parsed.segments[1].type)
                assert.are.equal("id", parsed.segments[1].accessor)
                assert.are.equal("frame", parsed.segments[2].type)
                assert.are.equal("index", parsed.segments[2].accessor)
                assert.are.equal(0, parsed.segments[2].value)
            end)

            it("should parse full hierarchical path with index", function()
                local parsed = uri.parse("dap:session:fluffy-kitten/thread:1/stack:1/frame[0]")
                assert.is_not_nil(parsed)
                assert.are.equal(4, #parsed.segments)
                assert.are.equal("session", parsed.segments[1].type)
                assert.are.equal("id", parsed.segments[1].accessor)
                assert.are.equal("thread", parsed.segments[2].type)
                assert.are.equal("id", parsed.segments[2].accessor)
                assert.are.equal("stack", parsed.segments[3].type)
                assert.are.equal("id", parsed.segments[3].accessor)
                assert.are.equal("frame", parsed.segments[4].type)
                assert.are.equal("index", parsed.segments[4].accessor)
                assert.are.equal(0, parsed.segments[4].value)
            end)

            it("should parse variable[0]", function()
                local parsed = uri.parse("dap:session:xxx/frame:42/scope:Locals/variable[0]")
                assert.is_not_nil(parsed)
                assert.are.equal(4, #parsed.segments)
                assert.are.equal("variable", parsed.segments[4].type)
                assert.are.equal("index", parsed.segments[4].accessor)
                assert.are.equal(0, parsed.segments[4].value)
            end)
        end)

        describe("error cases", function()
            it("should return nil for invalid URIs", function()
                assert.is_nil(uri.parse("invalid"))
                assert.is_nil(uri.parse("http://example.com"))
                assert.is_nil(uri.parse("dap:"))
                assert.is_nil(uri.parse(""))
            end)

            it("should return nil for malformed segments", function()
                -- Bare type in middle is invalid (only allowed as last segment)
                assert.is_nil(uri.parse("dap:session/thread:1"))  -- session has no accessor, but it's not last
            end)

            it("should parse bare type as last segment (all items)", function()
                -- Bare type as last segment means "all of this type"
                local parsed = uri.parse("dap:session")
                assert.is_not_nil(parsed)
                assert.are.equal("session", parsed.segments[1].type)
                assert.is_nil(parsed.segments[1].accessor)
                assert.is_nil(parsed.segments[1].value)

                -- Scoped: all threads in a session
                parsed = uri.parse("dap:session:foo/thread")
                assert.is_not_nil(parsed)
                assert.are.equal("thread", parsed.segments[2].type)
                assert.is_nil(parsed.segments[2].accessor)
            end)
        end)

        describe("encoding", function()
            it("should decode percent-encoded segments", function()
                local parsed = uri.parse("dap:session:fluffy-kitten/variable:foo%3Abar")
                assert.is_not_nil(parsed)
                assert.are.equal("foo:bar", parsed.segments[2].value)
            end)
        end)
    end)

    describe("build()", function()
        it("should build session URI", function()
            local result = uri.build("session", "fluffy-kitten")
            assert.are.equal("dap:session:fluffy-kitten", result)
        end)

        it("should build session/frame URI", function()
            local result = uri.build("session", "fluffy-kitten", "frame", "42")
            assert.are.equal("dap:session:fluffy-kitten/frame:42", result)
        end)

        it("should build session/thread/stack URI", function()
            local result = uri.build("session", "fluffy-kitten", "thread", "1", "stack", "3")
            assert.are.equal("dap:session:fluffy-kitten/thread:1/stack:3", result)
        end)

        it("should encode special characters", function()
            local result = uri.build("session", "fluffy-kitten", "variable", "foo:bar")
            assert.are.equal("dap:session:fluffy-kitten/variable:foo%3Abar", result)
        end)

        it("should error on odd number of arguments", function()
            assert.has_error(function()
                uri.build("session")
            end)
        end)
    end)

    describe("build_indexed()", function()
        it("should build URI with index accessor", function()
            local result = uri.build_indexed("session", "fluffy-kitten", "frame", 0)
            assert.are.equal("dap:session:fluffy-kitten/frame[0]", result)
        end)

        it("should mix id and index accessors", function()
            local result = uri.build_indexed("session", "fluffy-kitten", "thread", "1", "stack", "1", "frame", 0)
            assert.are.equal("dap:session:fluffy-kitten/thread:1/stack:1/frame[0]", result)
        end)

        it("should handle pure index URI", function()
            local result = uri.build_indexed("frame", 0)
            assert.are.equal("dap:frame[0]", result)
        end)
    end)

    describe("build_file()", function()
        it("should build file:// URI", function()
            local result = uri.build_file("/home/user/app.py")
            assert.are.equal("file:///home/user/app.py", result)
        end)
    end)

    describe("validate()", function()
        it("should validate correct file URIs", function()
            local valid, err = uri.validate("file:///home/user/app.py")
            assert.is_true(valid)
            assert.is_nil(err)
        end)

        it("should validate correct dap URIs with :id", function()
            local valid, err = uri.validate("dap:session:fluffy-kitten")
            assert.is_true(valid)
            assert.is_nil(err)

            valid, err = uri.validate("dap:session:fluffy-kitten/frame:42")
            assert.is_true(valid)
            assert.is_nil(err)
        end)

        it("should validate correct dap URIs with [n]", function()
            local valid, err = uri.validate("dap:frame[0]")
            assert.is_true(valid)
            assert.is_nil(err)

            valid, err = uri.validate("dap:session:xxx/frame[0]")
            assert.is_true(valid)
            assert.is_nil(err)
        end)

        it("should reject invalid schemes", function()
            local valid, err = uri.validate("http://example.com")
            assert.is_false(valid)
            assert.is_not_nil(err)
        end)

        it("should reject empty file URIs", function()
            local valid, err = uri.validate("file://")
            assert.is_false(valid)
            assert.is_not_nil(err)
        end)
    end)

    describe("encode_segment() / decode_segment()", function()
        it("should encode colons", function()
            assert.are.equal("foo%3Abar", uri.encode_segment("foo:bar"))
        end)

        it("should encode slashes", function()
            assert.are.equal("foo%2Fbar", uri.encode_segment("foo/bar"))
        end)

        it("should encode percent signs", function()
            assert.are.equal("100%25", uri.encode_segment("100%"))
        end)

        it("should decode percent-encoded strings", function()
            assert.are.equal("foo:bar", uri.decode_segment("foo%3Abar"))
            assert.are.equal("foo/bar", uri.decode_segment("foo%2Fbar"))
            assert.are.equal("100%", uri.decode_segment("100%25"))
        end)

        it("should round-trip encode/decode", function()
            local original = "foo:bar/baz%qux"
            local encoded = uri.encode_segment(original)
            local decoded = uri.decode_segment(encoded)
            assert.are.equal(original, decoded)
        end)
    end)

    describe("schema", function()
        it("should define all entity types", function()
            assert.is_not_nil(uri.schema.session)
            assert.is_not_nil(uri.schema.thread)
            assert.is_not_nil(uri.schema.stack)
            assert.is_not_nil(uri.schema.frame)
            assert.is_not_nil(uri.schema.scope)
            assert.is_not_nil(uri.schema.variable)
            assert.is_not_nil(uri.schema.source)
            assert.is_not_nil(uri.schema.breakpoint)
            assert.is_not_nil(uri.schema.binding)
            assert.is_not_nil(uri.schema["source-binding"])
            assert.is_not_nil(uri.schema["filter-binding"])
            assert.is_not_nil(uri.schema.output)
        end)

        it("should define scopes for hierarchical entities", function()
            assert.is_not_nil(uri.schema.thread.scopes)
            assert.is_not_nil(uri.schema.thread.scopes.session)

            assert.is_not_nil(uri.schema.frame.scopes)
            assert.is_not_nil(uri.schema.frame.scopes.session)
            assert.is_not_nil(uri.schema.frame.scopes.thread)
            assert.is_not_nil(uri.schema.frame.scopes.stack)
        end)
    end)
end)
